### ISSUE TITLE
Map is empty

### ISSUE THREAD

**Issue by Etenil** [bailuk/AAT#1]
Hi there,

I've installed AAT 0.8 alpha through F-Droid on Cyanogenmod 10. The maps stay empty with no tiles showing. I've followed osmdroid's help on downloading an atlas of tiles and placing it in the osmdroid tiles directory in AAT's settings, but to no effect.

What should I do to get AAT to display tiles on the map?

**Comment by bailuk** [comment]
Use "Menu->Map Tiles" to select tiles. By default there are none selected.

**Comment by Etenil** [comment]
Ah thanks, that fixes it indeed.
