### ISSUE TITLE
Speed plot: Legend and Colors

### ISSUE THREAD

**Issue by Heineken** [bailuk/AAT#10]
I have three curves in the velocity diagram. 
1. The grey one is hardly visible on the grey background. 
2. There is no legend. I assume the smoother ones are moving averages, right? That should be explained somewhere.
3. Does the average including or exclude pauses?

**Comment by bailuk** [comment]
Grey: max speed of plotted sample
Blue: total average at this distance
Orange: average speed of plotted sample

3. Pauses that come from the tracker engine are subtracted from time. The new post processed pauses are not subtracted but I can change this easily.

**Comment by Heineken** [comment]
Thanks for the explanation.
What's the "plotted sample"? A moving time window?
3. Not sure if I understood this. Is this is a yes? So, the curves correspond to the overall average shown in the summary?

**Comment by Heineken** [comment]
I discovered by accident that the legend is displayed when I tap the lower part of the graph.
