### ISSUE TITLE
privacy policy update

### ISSUE THREAD

**Issue by mpaolo** [bailuk/AAT#100]
Hi,

seems you have included org.acra tracker at some point, thus the PP should be amended accordingly. At present it says: 

```
Crash reports
The developer is unable to get crash reports automatically when the app crashes. ...
```

I think acra allows for such automatic sending (where? which server?) albeit upon user's choice/confirmation?

thanx

**Comment by bailuk** [comment]
Hi,

ACRA is configured to send crash reports with e-mail **manually, with and only with the interaction of the user**. 
This means a dialog gets displayed that gives the user a choice to "cancel" or to open the standard e-mail program to edit and then send an mail with a stack trace attached. The stack trace is a text file that can be displayed with any text-editor.
See here on how ACRA is configured: https://github.com/bailuk/AAT/blob/master/app/src/main/java/ch/bailu/aat/App.java

For me ACRA is very useful: so far it helped me to fix many bugs efficiently. 

Also ACRA https://www.acra.ch/ is open source and on GitHub https://github.com/ACRA/acra.

**Comment by mpaolo** [comment]
Hi,

yep, perfect - you may want to just copy-n-paste your answer mostly as-is into the **Crash reports** paragraph in https://github.com/bailuk/AAT/blob/master/Privacy%20policy.md and you're done :)
Till you change things, that is.
Point is that checking app with e.g. classyshark3xodus it shows 1 tracker since some version update whereas there were none before. One may wonder what's it for, so better mention it upfront in the PP doc.

thanx
