### ISSUE TITLE
Altitude not recorded

### ISSUE THREAD

**Issue by ANDREW007CZ** [bailuk/AAT#105]
Hi,
very nice app!
But I'm not able to record altitude on my Xperia X Compact (Oreo 8.0). Everything else is OK. I can't figure out what could be an issue there. 
Also a suggestion for further development: some statistics overview would be cool (like "the fastest", "the longest trip this month/ever"

**Comment by bailuk** [comment]
Hi,
What version of AAT are you using?
Does altitude gets displayed while recording a track?

**Comment by ANDREW007CZ** [comment]
Hi,
1.19 (latest on F-droid)
The altitude is not displayed in both cases - not in "standby" and not in recording mode. Wierdly, it only shows barometer altitude. Or does it normally not get altitude from GPS? Yesterday for a moment I saw a value in altitude (Barometer) that was quite OK for my location. But usually it only shows 0.
![Screenshot_20210102-133149](https://user-images.githubusercontent.com/26521196/103462691-5b8d9200-4d27-11eb-9970-7310cf5a6f54.png)
![Screenshot_20210102-133112](https://user-images.githubusercontent.com/26521196/103462693-5cbebf00-4d27-11eb-8ed4-a08705b9251e.png)

**Comment by bailuk** [comment]
Hi,
AAT normally uses GPS for altitude unless the builtin barometer device is activated in AAT's settings.
Just go to Preferences->General/System, scroll down to Sensors and uncheck "Internal barometer sensor" .

If you want to use barometer for altitude, you have to provide precise altitude at least before each trip. 
You can just tab the altitude display in the cockpit view to enter altitude of your current location.

Altitude from air pressure is more precise than GPS, but depends on some manual maintenance.

I hope everything works now.

**Comment by ANDREW007CZ** [comment]
Hi, yes! Thanks! Didn't realize this. Everything is working great now. :)
