### ISSUE TITLE
Labelling

### ISSUE THREAD

**Issue by Heineken** [bailuk/AAT#11]
There are some feature mysterious to me:
1. Nominatim: Googling taught me it's OSM's geocoding search engine. Maybe name it "search map" or something self-explaining?
2. What does "Screen off/dark/bright" do?
3. What is the difference between Cockpit A and B?

**Comment by bailuk** [comment]
1. How about "Search map (Nominatim)"
2. Turn screen off  when tracking / Dim back light but keep screen on when tracking (only on some older devices) / keep screen on when tracking
3. A short cot to one of the two standard Cockpits (A is full screen and B is split screen with map)

**Comment by Heineken** [comment]
1. Good.
2. OK, well then it doesn't turn off the screen (or does it?), but optionally prevents the phone from doing so. Maybe better label it "System default/keep on (dark)/keep on (bright)"
3. -> "Full screen cockpit" / "Split screen cockpict" ?

**Comment by bailuk** [comment]
I think this can be closed.

Else open a new issue. Also see #22 on how to contribute translations and change resource strings.
