### ISSUE TITLE
Close app only via Task Manager

### ISSUE THREAD

**Issue by Heineken** [bailuk/AAT#12]
After starting AAT without tracking, my GPS is not turned off until I kill AAT in the task manager.
GPS is a potentially unwanted battery drain. Is that the intended behaviour?
Expected behaviour: 
Sending AAT to the background deactivates GPS unless tracking is active.
OR
Repeatedly pressing back eventually closes the app and switches off GPS.

**Comment by bailuk** [comment]
It's not intended behavior, unless you've enabled GPS-lock (tap the GPS status view to toggle GPS-lock)

**Comment by Heineken** [comment]
Cannot confirm. GPS stays on even without GPS lock.

**Comment by bailuk** [comment]
I can't reproduce this. GPS always turns of after a few seconds when app is not on display and tracker is off (stopped). 
For some reason AAT never releases resources on your device. Can you give me some more information? Does this always happen? What happens if you just open the main screen and then immediately close it again with the back button?

**Comment by Heineken** [comment]
Yes, it always happens, even right after launching the app.
It's on a Xperia Z3c with Android 6.0.1 (rooted stock rom)
How else can I help?

**Comment by Heineken** [comment]
Same on Motorola Defy+ running SlimKat Rom (Android 4.4).

**Comment by YuhanXu** [comment]
Same on Motorola Moto X 2013, GPS keeps toggling on and off even the tracker is off.

**Comment by bailuk** [comment]
I've added log messages to the latest release to track this issue. 
If someone could send logcat output that would be very helpful.

**Comment by Heineken** [comment]
Where would I find that log? aat_data/log is empty.
I updated today and tracked for a couple of hours.

**Comment by bailuk** [comment]
You can use [adb](https://developer.android.com/studio/command-line/adb.html) and [logcat](https://developer.android.com/studio/command-line/logcat.html) from the Android SDK to save debug messages. There are also apps on f-droid that let you view / save log messages.

**Comment by Heineken** [comment]
OK. I started alogcat and set it to verbose level "debug", then started AAT 1.9β, waited for the Locator Icon to show, then exited and killed the app. Logcat only shows an idle message.

**Comment by Heineken** [comment]
OK, I checked again. GPS is switched off with a delay of about 12 seconds. On three different phones.
