### ISSUE TITLE
Step sensor in LG G5 stopped working

### ISSUE THREAD

**Issue by jgeisler0303** [bailuk/AAT#123]
Hi,
first let me say that AAT is the best! I tried all the other trackers on f-droid and always returned to AAT. Its easy to use yet full featured with access to all relevant data and settings. Thanks for all the work you put in it.

Now my problem: I use an LG G5 H850 with Lineage OS 18.1 with microg. It has an "Internal QTI LGE Step Counter Sensor" and an "Internal QTI LGE Step Counter -Wakeup Secondary" both of which I can connect to in the Settings. But the steps don't get recorded.
This used to be different until the beginning of May 2021. I'm not sure what changed there to cause this.

Are there any logs I can send you to facilitate the debugging?

I also noticed that AAT doesn't ask for the activity sensor permission. Is that a potential problem?

Finally, I am a runner and I usually use cockpit A. Would it be possible to exchange the cadence gauge for a step counter gauge when the profile is "7.0 Jogging"?

Cheers,
JG

**Comment by bailuk** [comment]
See Issue #124

**Comment by bailuk** [comment]
I assume this was a permission problem.
