### ISSUE TITLE
Bug: Step senzor connected but no steps counted

### ISSUE THREAD

**Issue by ANDREW007CZ** [bailuk/AAT#124]
A12
SONY Xperia 5 III
AAT version  1.21

Steps are not counted in recording despite step-counting hardware is connected.
There are always 0 steps.

I didn't have this problem on my older Xperia X Compact while having all the same app settings.

**Comment by bailuk** [comment]
Looks like Google has added a permission for Physical activity recognition: https://developer.android.com/about/versions/10/privacy/changes#physical-activity-recognition

At least this could be the cause of disappearing step counter.

**Comment by ANDREW007CZ** [comment]
This is fixed in latest release. Thanks so much, bailuk! :)
