### ISSUE TITLE
Possible bugs or documentation issues

### ISSUE THREAD

**Issue by peternewman** [bailuk/AAT#128]
Trying to set this up for my dad on an ageing LG(?) on Android 4.4, firstly thanks very much for the app, it seems to do exactly what he needs, once we got the hang of it. So it's great to be able to still use the older device.

A few issues I hit though

1. OSM POI search through a TLS error and didn't work, which I suspect is probably to be expected due to the age of the device?
2. Online maps silently failed, I assume again due to the above?
3. Two start buttons appear in the menu initially, but I think only the top one worked. Once you're recording they become pause and stop
4. I had a real struggle getting the offline maps to work. I was looking at https://bailu.ch/aat/doc/ and somehow got the theme working okay after a bit with it stored in (paraphrasing from memory here) /Android/data/ch.bailu.aat/files where I'd created a maps folder and put them, initially both in a subfolder and directly. But I couldn't ever get maps working there. After looking at some of the code, I then tried /aat_data/maps and that worked fine. If that's the intention, it would be good to add them to https://github.com/bailuk/AAT/blob/master/README.enduser.md#where-to-find-files and maybe put the full path in https://github.com/bailuk/AAT/blob/master/README.enduser.md#install-offline-maps . I think I had also created a new folder locally at this point rather than copying the folder from Windows onto the device but I assume that's a red herring.
5. I was a bit confused why the map didn't jump to my position when it first got a GPS lock or anything and likewise why the import/export location didn't have a means to jump to the GPS location. Having just re-read the readme, I've now found that's hidden at the bottom edge. Would it make sense to lock to current position by default, and e.g break away when you pan around (as StreetComplete does), at least then people would see what they expect when they first start? Or at least jump to the local area when the first GPS lock is obtained (especially if the user hasn't touched the map location.

**Comment by peternewman** [comment]
Oh also you link to https://www.openandromaps.org/ it would be good to confirm on the documentation that V5 maps are fine (they seemed to work for me).

**Comment by bailuk** [comment]
Issue 1 and 2:

Android Version < 5 has limited support for TLS. 
Just tested in an emulator and only TLSv1 and SSLv3 are supported.

See also: https://ankushg.com/posts/tls-1.2-on-android/
The Workaround suggested here is not an option, as it makes AAT dependent on Google Play Services

One Workaround I could implement is to add additional map sources that use http instead of https. This works with mapnik and way marked trails.

**Comment by peternewman** [comment]
Thanks very much @bailuk we've updated to 1.24 now. Do you know roughly when the next release might arrive with the other fixes above in?

>     3. Two start buttons appear in the menu initially, but I think only the top one worked. Once you're recording they become pause and stop

This still seems to be present in 1.24 from what I could see, I couldn't see an obvious commit fixing it above.

> Issue 1 and 2:
> 
> Android Version < 5 has limited support for TLS. Just tested in an emulator and only TLSv1 and SSLv3 are supported.
> 
> See also: https://ankushg.com/posts/tls-1.2-on-android/ The Workaround suggested here is not an option, as it makes AAT dependent on Google Play Services

Ah that's a shame, I assume doing separate Google Play and F-droid variant releases would be a real hassle? I think StreetComplete does something similar, but maybe for more significant reasons than supporting ancient hardware.

> One Workaround I could implement is to add additional map sources that use http instead of https. This seems to work with mapnik.

Amazing thanks, hopefully they won't be turned off for a while! 🤞
