### ISSUE TITLE
Move tracks or allow debug

### ISSUE THREAD

**Issue by Xanatos00** [bailuk/AAT#164]
Hello,

Trying to recover GPX files from an activity recorded in /data/data/ch.bailu.aat/files/activity2
Unfortunately I don't have root access on this device.
Trying to restore it with workaround "adb backup" which fails because debug from AAT is not allowed.
Please I need some workaround about it.

Maybe judicious to remove /data/data/ for parameter data path file too.

**Comment by bailuk** [comment]
Do you want to backup files from `data/data/ch.bailu.aat/files` or restore files to  `data/data/ch.bailu.aat/files` ?

Can you specify what  adb command you have tried and what error message did you receive? 

`/data/data/ch.bailu.aat/files` is application specific storage and is managed by Android.

One workaround is to generally not use this path as data directory.  You can select any directory on the phones storage (internal, sdcard, ...) using SAF: `perferences->general/system->data directory->pick (SAF)...`

But if you already have files in `/data/data/ch.bailu.aat/files/` they do not get copied automatically so you have to find a way to to copy those.

**Comment by Xanatos00** [comment]
Hello,
I want backup GPX files before reset path parameters, at present day stored in /data/data/ch.bailu.aat/files/activity2

Sure:
`adb backup -noapk ch.bailu.aat
// encrypted device, so
java -jar abe.jar unpack backup.ab backup.tar
ls
549  9 juil. 07:38 backup.ab
1024  9 juil. 07:53 backup.tar`

Absolutely, that's my issue.
For some reason, one month ago, AAT was not able to write in my original folder (/emulated/0/t_data/), the only folder working was /data/data/ch.bailu.aat

**Comment by davidovitch** [comment]
I experienced the same on Android 11: after an update of AAT my existing folder was no longer accessible for AAT and I switched to `/Android/data/ch.bailu.aat/files` without really thinking about it. However, other apps can not access this folder even if they have the permissions to access the storage device (I use rsync in termux to create backups of my phone). The `/Android/data/ch.bailu.aat/files` directory is accessible when connected to a computer (Linux in my case) via USB and file sharing activated on the device and that allowed me to move the files from `/Android/data/ch.bailu.aat/files` to my previous AAT directory. Then I could change back to the previous directory in AAT using SAF (this directory is visible in termux so I can make backups). Problem solved :+1:

**Comment by Xanatos00** [comment]
Hello,
I found a workaround to copy files from /data/data/ch.bailu.aat/*
I using another app I wanted to share a file and accidentally discover a file explorer window which allow to pick files from other apps ; i.e. has right to access files ; See below

I don't know if it's TouchWiz/Android WebView/another component.
