### ISSUE TITLE
Tracker does not start

### ISSUE THREAD

**Issue by gandogar** [bailuk/AAT#18]
Hello,
I used aat 'track your activities' version 1.9 beta on android 7.1.1 device before, now version 1.10 beta.
When I start the tracker, it seems not to start in fact. There is no tracked route in the map, no distance is tracked and timer does not start. The actual position, velocity and altitude are displayed.
Stopping and restarting the tracker does not help.
I deleted and reinstalled aat app some times, but that does not help, too.

Any ideas, what I can do to start tracker correctly?
Need more information to this issue?

Gandogar

**Comment by bailuk** [comment]
Hi,

Which _location provider_ is selected inside AAT (preferences -> system) ?

**Comment by bailuk** [comment]
Most likely GPS uses a time zone other than UTC on your system. If so this will be fixed in 1.12.
