### ISSUE TITLE
NullPointerException when checking MapsForge and Mapnik for Map

### ISSUE THREAD

**Issue by mikg0** [bailuk/AAT#19]
Hi bailuk,

Thanks for this great software. (v1.10-beta on Lineage OS 14.1)
I found a minor issue that made me stumble at first, which might happen to other users. I could not see any map, so I checked the check box for Mapnik in addition to Mapsforge. I saw a map then, but each time I wanted to see the details for a track, AAT stopped.
Simple workaround: uncheck either one of the two tile services.
Below is a typical log that shows what happens.

Best regards and a happy new year!

12-27 19:14:56.442   959   986 I ActivityManager: Start proc 9714:ch.bailu.aat/u0a155 for service ch.bailu.aat/.services.OneService
12-27 19:16:22.373   959  4342 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=ch.bailu.aat/.activities.MainActivity bnds=[169,581][325,737] (has extras)} from uid 10035 on display 0
12-27 19:16:25.381   959  3164 I ActivityManager: START u0 {act=ch.bailu.aat.activities.TrackListActivity flg=0x4000000 cmp=ch.bailu.aat/.activities.TrackListActivity (has extras)} from uid 10155 on display 0
12-27 19:16:25.793  9714  9833 E AndroidRuntime: Process: ch.bailu.aat, PID: 9714
12-27 19:16:25.793  9714  9833 E AndroidRuntime: **java.lang.NullPointerException: Attempt to invoke virtual method 'boolean ch.bailu.aat.services.render.Renderer.supportsTile(org.mapsforge.core.model.Tile)' on a null object reference**
12-27 19:16:25.793  9714  9833 E AndroidRuntime: 	at ch.bailu.aat.services.render.Configuration.supportsTile(Configuration.java:66)
12-27 19:16:25.793  9714  9833 E AndroidRuntime: 	at ch.bailu.aat.services.render.RenderService.supportsTile(RenderService.java:87)
12-27 19:16:25.793  9714  9833 E AndroidRuntime: 	at ch.bailu.aat.map.tile.source.DoubleSource.decide(DoubleSource.java:43)
12-27 19:16:25.793  9714  9833 E AndroidRuntime: 	at ch.bailu.aat.map.tile.source.DoubleSource.getID(DoubleSource.java:34)
12-27 19:16:25.793  9714  9833 E AndroidRuntime: 	at ch.bailu.aat.map.tile.TileProvider.getTileHandleLevel2(TileProvider.java:164)
12-27 19:16:25.793  9714  9833 E AndroidRuntime: 	at ch.bailu.aat.map.tile.TileProvider.getTileHandle(TileProvider.java:152)
12-27 19:16:25.793  9714  9833 E AndroidRuntime: 	at ch.bailu.aat.map.tile.TileProvider.get(TileProvider.java:69)
12-27 19:16:25.793  9714  9833 E AndroidRuntime: 	at ch.bailu.aat.map.tile.TileProvider.preload(TileProvider.java:63)
12-27 19:16:25.793  9714  9833 E AndroidRuntime: 	at ch.bailu.aat.map.mapsforge.MapsForgeTileLayer.draw(MapsForgeTileLayer.java:72)
12-27 19:16:25.793  9714  9833 E AndroidRuntime: 	at ch.bailu.aat.map.mapsforge.MapsForgeTileLayer.draw(MapsForgeTileLayer.java:55)
12-27 19:16:25.793  9714  9833 E AndroidRuntime: 	at ch.bailu.aat.map.mapsforge.MapsForgeTileLayerStack$SubLayers.draw(MapsForgeTileLayerStack.java:160)
12-27 19:16:25.793  9714  9833 E AndroidRuntime: 	at ch.bailu.aat.map.mapsforge.MapsForgeTileLayerStack.draw(MapsForgeTileLayerStack.java:78)
12-27 19:16:25.795   959  4352 W ActivityManager:   Force finishing activity ch.bailu.aat/.activities.TrackListActivity
12-27 19:16:25.800   959  4352 W ActivityManager:   Force finishing activity ch.bailu.aat/.activities.MainActivity
12-27 19:16:25.855   959  3435 I WindowManager: WIN DEATH: Window{cd3ad5e u0 ch.bailu.aat/ch.bailu.aat.activities.TrackListActivity}
12-27 19:16:25.856   959  4347 I ActivityManager: Process ch.bailu.aat (pid 9714) has died

**Comment by bailuk** [comment]
Thanks for the bug report.
A fix for this issue will be in v1.11-beta.
