### ISSUE TITLE
Need more slots

### ISSUE THREAD

**Issue by Heineken** [bailuk/AAT#21]
I happily use AAT for tracking my trips hiking/jogging, on road/mountain/trekking bike, canoe, on ice/inline skates, on cross country/randonnée/downhill skis. I keep them sorted by labeling, but I'd prefer having an activity slot for each one.
I know I sound a little hyperactive. It's a tough life :-)
Is there any chance we could have more than the current 5 activity slots?

**Comment by bailuk** [comment]
I could just increase the number of activity slots to 15 if you want (if that's enough for you). 
Of course then I have to reorganize the settings dialog a bit.

**Comment by Heineken** [comment]
Thanks for the quick implementation!
Wow, a lot of changes in this commit for just increasing one number.
That would work for me, but such a long list is not really pretty, is it?
Would be nicer to leave it at 5 and make it possible to add/remove slots.
If that's too much hassle in the GUI, another idea is to let the user do it manually via adding/removing the folders.

**Comment by bailuk** [comment]
I basically did what you're suggesting. The user can now set another value (instead the default 5) in the range from 3 to 15.

**Comment by Heineken** [comment]
Sounds good! Looking forward for the release...
