### ISSUE TITLE
Use of phone's barometer for altitude

### ISSUE THREAD

**Issue by tomdereub** [bailuk/AAT#26]
I think the app only uses GPS to determine altitude ? Is it possible to add the use of the barometer, which is much more precise to calculate total ascend and descend ? And the most would be the possibility to calibrate altitude before start.
In my case, I have errors of about 70 meters on altitudes, and not really constant.

**Comment by bailuk** [comment]
Altitude from barometer should work now:

This can be activated and calibrated in the preferences. There is now a list of supported sensors in the preferences view: just activate the internal barometer.  To calibrate the altitude you can also tap on the altitude display in the cockpit view.
