### ISSUE TITLE
Tracker doesn't start because of an android.permission issue

### ISSUE THREAD

**Issue by mrpewpew** [bailuk/AAT#28]
After updating to AAT v1.14, I get this error each time I try to start the tracker : 
`SecurityException: Neither user 10138 nor current process has android.permission.WAKE_LOCK.`

I had to revert to v1.13 for the time being. I am on LineageOS 15.1 - Android 8.1.0

**Comment by bailuk** [comment]
And why does it work in v1.13?

**Comment by bailuk** [comment]
Found it! This bug has been introduced by integrating ACRA library.
See this post on stackoverflow: [https://stackoverflow.com/a/50972790](https://stackoverflow.com/a/50972790)

**Comment by bailuk** [comment]
A new release will follow soon.

**Comment by mrpewpew** [comment]
Thanks for the fix ! I'll wait for the Fdroid release
