### ISSUE TITLE
No map on samsung sm-g313h

### ISSUE THREAD

**Issue by mrjspb** [bailuk/AAT#3]
Hi!

I'm using 1.0 beta version of your app, and i like it very much.

Though, there is no map shown in app, but there are files in tile cache directory: /storage/emulated/0/aat_data/tiles/Mapnik/11/ there are two subdirs 1195 and 1196 with 2 files in each.  

Phone samsung sm-g313h, android 4.4.2

If it's possible -- one suggestion for feature: add way to precache map tiles for imported track up to some detail level. It can be used while going to forest ride where is poor or no internet connection at all.

**Comment by mrjspb** [comment]
Oh, sorry, hank you very much for your app

**Comment by bailuk** [comment]
You have to select one or more map tile layers first:
**App Menu (most bottom left button on your phone) -> Map -> (list of map tile layers)**

Precaching:
- Select your imported track for mock location (long press inside file list view opens context menu). 
- Enable mock location as GPS provider in preferences and restart app.
- Start tracking with map view open.

Also keep in mind that AAT does not delete (or update) any downloaded map tiles.

**Comment by mrjspb** [comment]
Thank you!
I see -- in 4+ android i need to longpress the applist key to open menu, so I just haven't realize that menu been there. Maybe it would be good idea to add menu button on top?

Once again, thanks for good app.
