### ISSUE TITLE
SecurityException: Permission Denial: requires android.permission.FORGROUND_SERVICE

### ISSUE THREAD

**Issue by moneyninja** [bailuk/AAT#31]
I've only just discovered your app but the last version and newly released 1.14.1 both display 'SecurityException: Permission Denial: startForeground from pid=25829, uid=10149 requires android.permission.FORGROUND_SERVICE'

Android Pie (9.0) on Oneplus 3T and in the android emulator, have given permission for Location and Storage.

Thanks

**Comment by bailuk** [comment]
android.permission.FORGROUND_SERVICE has been introduced in Android 9.

This is fixed now but there are probably more issues related to newer Android versions.
