### ISSUE TITLE
Wrong tracked activity when GPS signal is lost

### ISSUE THREAD

**Issue by mrpewpew** [bailuk/AAT#39]
Hello, I am using your application to track my running sessions and I noticed that if the GPS signal gets lost during the session (e.g going in a tunnel), the tracked activity is wrongly recorded. AAT seems to only record the time passed when the GPS signal was lost and with an erratic path.
Is there a fix for this ?

**Comment by bailuk** [comment]
Hi,

What exactly is wrong or missing in your recorded track? 
How does total time and average time differ from reality?
Are there any other track segments missing or wrong (besides the tunnel part)? 

In the preferences you can set the **accuracy filter** to a low value. This way only GPS information with a certain precision gets recorded.

**Comment by mrpewpew** [comment]
It only records the tunnel part in a erratic way and discards the rest of the track. It means that if I passes through a tunnel, I loose everything except the few seconds I am in the tunnel. The total time is also only the time spent in the tunnel. I will try the accuracy filter to see if it mitigates the problem

**Comment by bailuk** [comment]
Now that's a strange bug. I've never seen this before.

What filter options do you have enabled? (Such as distance filter, auto-pause etc)

If you open the recorded GPX file in a simple text editor everything should be present including the part before  and after the tunnel. Maybe you'll find a possible cause for this bug this way...

If you want you can also send me a broken GPX track by e-mail. That would help me a lot.

**Comment by bailuk** [comment]
The GPX file you have sent me has no errors. The tracker really only recorded the tunnel part.

It looks like AAT does not receive precise GPS signal for some reason.

- What GPS provider is selected in AATs preferences dialog? (You can select between "**System GPS**, **Network**, **System GPS and Network** and **Mocklocation**). Set this to **System GPS**.
- Does the phones GPS status icon get's displayed in the phones status bar? 
- Does AAT have permission to access GPS? (You can change this in the phones system settings)
- Does the current location gets displayed correctly with a small orange circle inside the map view?

**Comment by bailuk** [comment]
I think this is resolved so a close this issue.
