### ISSUE TITLE
Additional Sensors via ANT+/Bluetooth LE

### ISSUE THREAD

**Issue by watchingJu** [bailuk/AAT#41]
Hello,

as stated here [1] I'll open a new feature request which might be interesting for this app.

Some commercial products (Strava, Wahoo) already implemented the use of additional sensors for cadence, speed and heart rate. These data is interesting not only for road bike training and require additional tools (like these [2]) which are paired over Bluetooth LE/Smart [3] or ANT/ANT+ [4]. Many smartphones already support these technologies, if not USB dongles can be used.

Sadly I'm not used to develop apps, or knowing much about licensing, but maybe this page [5] can help with research on how to implement it.

Cheers

[1] https://github.com/bailuk/AAT/issues/6#issuecomment-396030556
[2] https://eu.wahoofitness.com/devices/bike-sensors
[3] https://en.wikipedia.org/wiki/Bluetooth_Low_Energy
[4] https://en.wikipedia.org/wiki/ANT%2B
[5] https://www.thisisant.com/developer/ant/ant-in-android

**Comment by arsab** [comment]
more reference which might help:
Including timer rolling:
https://developer.polar.com/wiki/Cycling_Speed_%26_Cadence

**Comment by bailuk** [comment]
Some internal sensors and BluetoothLE sensors are now supported.

Type of devices supported:
- Barometer
- Heart rate
- Speed
- Cadence
