### ISSUE TITLE
Invalid GPX file after updating to last version

### ISSUE THREAD

**Issue by sepen** [bailuk/AAT#44]
First of all congrats for such a nice app for Android. Thanks for your work!!

After the last update, every time I track a new route and generate a .gpx file, it appears corrupt. I have to edit those files to fix the problem.

I compared current .gpx files with old ones I have and I see that now it records latitude and longitude with decimal format separated by a comma instead of a dot char. For example, latitude is recorded as lat="39,462721", when it should be lat="39.462721".

**Comment by bailuk** [comment]
This should be fixed in 1.15.1
