### ISSUE TITLE
Document advanced setting options

### ISSUE THREAD

**Issue by craftyguy** [bailuk/AAT#47]
There are a few options under Activity settings that could use some explanation (e.g. what is it used for, what do the values mean), since their meaning/use is not intuitive to someone (like me) who has no experience with tracking/mapping and GPS:

- Distance filter

- Accuracy filter

- Missing trigger

Even having explanations for these in the readme would be sufficient, though ideally there would be some sort of help tooltip in the app itself.

**Comment by bailuk** [comment]
I've added the following tool-tips: 
- Distance filter: Only log a GPS sample if it has a minimal distance from the last sample.
- Accuracy filter: Only log a GPS sample if it has a minimal accuracy.
- Missing trigger: Set tracker to auto-pause if the GPS signal is lost for a certain period.
