### ISSUE TITLE
Remove gpx tracks from overlays slot

### ISSUE THREAD

**Issue by GitKalle** [bailuk/AAT#49]
Hello, thanks for this application. I use it every time for my sports activities.

However, I try to play with the overlay feature. Now I have two gpx tracks as overlays in the overlay slots. On every recorded track I can see this overlays on my recorded activities.

How can I remove the gpx tracks from the overlay slots?

**Comment by bailuk** [comment]
Tap the right area in the (any) map view. Some icons appear on the right side. Open the map menu (icon on top). Select overlays. Enable or disable overlays as wanted.

**Comment by GitKalle** [comment]
Perfect it works.
I'm very impressed about the hidden menu with more functionality. I especially like the graph related to the gpx points.

Keep up the good work.
