### ISSUE TITLE
Ability to export GPx to Strava

### ISSUE THREAD

**Issue by arsab** [bailuk/AAT#55]
Thanks,
Very practical and apreciate also much new BLE features.

Just one point: I can not export directly the GPX file to Strava unless loosing HR record.
need to change it manually in editor prior to export.

![Sans titre](https://user-images.githubusercontent.com/38669282/59551592-4d78f480-8f7c-11e9-8f88-39055027fbab.jpeg)

**Comment by arsab** [comment]
With Changes to fix issue: https://github.com/bailuk/AAT/issues/56
Could get Cadence in GPX.
Similarly to "HR" could not import  "Cadence"  into Strava. directly, but with similar reedit.

GPXSee has an example of read parsing (maybe de facto standard?)
https://github.com/tumic0/GPXSee/blob/master/src/data/gpxparser.cpp
See lines 89 to 106

**Comment by bailuk** [comment]
I don't use Strava so i don't know anything about supported file formats.

This seems to be a Garmin extension: Garmin gpxtpx. Have you more information about this? A reverence file for testing? 

Maybe Strava is also compatible to other (more popular / more simple) extensions.

**Comment by arsab** [comment]
Please find attached an export of Strava site with **records made from Strava Application**.

Their site highlight their import capability but I have no clue on format of the different suppliers.
https://support.strava.com/hc/en-us/articles/223297187-How-to-get-your-Activities-to-Strava

The following site may also give some insight on other developments learning.
https://github.com/jonasoreland/runnerup/blob/master/app/src/org/runnerup/export/format/GPX.java

[Cycling Strava.txt](https://github.com/bailuk/AAT/files/3346677/Cycling.Strava.txt)

**Comment by arsab** [comment]
greating simple extension can be imported to Strava with "right" strings: "heartrate", "cadence"  see attachment.

[2019_06_29-simple-hr-cadence.txt](https://github.com/bailuk/AAT/files/3347188/2019_06_29-simple-hr-cadence.txt)

**Comment by bailuk** [comment]
The problem just was that the attribute keys were not lower case. It should work now.

**Comment by arsab** [comment]
thanks for the progress however needed to replace "hr" by "heartrate" as per note:
(unfortunately more characters in the file ;-(

https://developers.strava.com/docs/uploads/

Strava also detects general tags placed in the <extensions> tag of each tag. Strava extracts:
cadence 
distance 
heartrate 
power

**Comment by arsab** [comment]
Great, Thanks,
Now can export both "heartrate" and "cadence" to Strava.
I will now close it.
