### ISSUE TITLE
BLE Cadence & Speed sensor issue

### ISSUE THREAD

**Issue by arsab** [bailuk/AAT#56]
In my case the HR sensor work as expected but

the Cadence & Speed sensor state to have connected  but does not show value nor record Gpx
(it is able to report data to other applications)

These does not show yet on the release note but will be nice features moving forward

**Comment by arsab** [comment]
I tried to debug and found few point which might help:
I have Sunding - 515 which is quite standard, I made Arduino driver for ESP32
http://www.sunding.com/en/plus/view.php?aid=45.

By putting traces and changing few simple code: I do not master Android ;-(
realized that the main issue for that is on setting of following flags:
- isSpeedSensor
- isCadenceSensor
By forcing both to "true" since I have both functions, I start to get cadence displayed.

**Comment by arsab** [comment]
Got it : the bit 2 on CSC Feature is more about location rather then capability so changing readCscFeature as follows solve the problem.

    private void readCscFeature(byte[] v) {
        if (v.length > 0) {
            byte b = v[0];
            isCadenceSensor = ID.isBitSet(b, BIT_CADENCE);
            isSpeedSensor = ID.isBitSet(b, BIT_SPEED);
        }
    }


  | Bit |   |   | CSC Feature Bit |   |   | Static Requirement |  
-- | -- | -- | -- | -- | -- | -- | -- | --
0 | Wheel Revolution Data Supported | Lifetime
1 | Crank Revolution Data Supported | Lifetime
2 | Multiple Sensor Locations Supported | Lifetime
3-15 | Reserved for Future Use | Not defined.

**Comment by bailuk** [comment]
Thank you for this detailed bug report. Detection of multiple sensors should now work.
