### ISSUE TITLE
Set data recording frequency

### ISSUE THREAD

**Issue by benoit-dd** [bailuk/AAT#57]
As I understand, the log adds a data line every second in the gpx file.
I'd like to be able to chose between "every second"(by default), "every 10 second" or "every minute", if I want a lower precision/file sise.

**Comment by bailuk** [comment]
To lower GPX file size you can ...

- Select another GPS provider in "Settings / GPS". Select "System GPS 3000ms" tho have a sample every 3 seconds.

- Select a distance filter in "Settings / Presets for your activity". A sample will only be recorded if you have moved at least X meter.
