### ISSUE TITLE
Wish list

### ISSUE THREAD

**Issue by Heineken** [bailuk/AAT#6]
Hello,
I hope this repo is active, because this seems to be the 1st issue. Looking for a replacement for MyTracks I tried AAT today. I like the style, seems to work fine and quick. Here's my feature wish-list:
- cumulated vertical meters (I know it's tricky/arbitrary, maybe you can add vertical filter parameters to the settings)
- calorie calculation considering vertical meters or an explanation how it's done currently
- add openCycleMap overlay
to be continued ...

**Comment by bailuk** [comment]
- OpenCycleMap
It's a beautiful map but it needs a license key and one must pay for tile downloads. So it's not an option.
My focus is on off line maps. The next version of AAT will support [OpenAndroMaps](http://www.openandromaps.org/en/) and [Freizeitkarte](http://www.freizeitkarte-osm.de/android/en/index.html) which are both good maps for cycling.
- Cumulated vertical meters
It's definitely a feature that's missing
- Calories
I'll add the following to the README for clarification:
## Calculating calories
AAT uses the formula `hours * MET * weight` to calculate the kcal used for a specific activity.
MET stands for [metabolic equivalent](https://en.wikipedia.org/wiki/Metabolic_equivalent). The higher the value, the more energy you would use
for this specific activity. A complete list of activities and MET values can be found [here](https://sites.google.com/site/compendiumofphysicalactivities/Activity-Categories).

Both MET and weight can be provided in the settings dialog. The MET value is leading the activity's name. For example: ` 6.8 bicycling, leisure, moderate effort`

**Comment by Heineken** [comment]
> OpenCycleMap

Oh, I didn't know. I was mislead by the "Open".

> Cumulated vertical meters

I don't know if you're aware, but the calculated number depends largely on the applied filter (average, threshold) which is necessary due to the larger error of GPS altitude. There seems to be no established standard procedure and hence, there are no official numbers given for e.g. the Tour de France. I found out when I played around with data an compared values from Google Earth, GPSies and my Excel calculation. If you understand German, here's a little more about it:
http://blog.gpsies.com/article/206/hoehenmeter-gpsies-sucht-die-wahrheit
http://blog.gpsies.com/article/176/neue-methode-zur-berechnung-der-hoehenmeter

> hours * MET * weight

To make it consistent, better make it "time * MET * weight" and give the unit for MET [kcal/h/kg] or make it "time[hours] * MET * weight[kg]"

Ah, there is a README.enduser.md. Didn't find that the first time I was looking for docu. Is that that displayed in the app somewhere? Why not integrate it with the existing readme.md?

**Comment by bailuk** [comment]
I've added a "descend" and "ascend" filed in the cockpit and track summary for vertical meters. 
It uses two averaged altitudes to calculate altitude deltas. It's probably not super accurate but form first sight it doesn't look bad.

I've also added a slope field to the cockpit.

Some ideas to make calculations more accurate:
- Store altitude as float instead as short (will consume more memory)
- Add an option to adjust GPS altitude with SRTM altitude (use an averaged GPS to SRTM difference)

**Comment by Heineken** [comment]
Sounds cool, looking forward to testing it. 
What averaging do you apply? Could that be configurable? 
As mentioned above, that can change results dramatically and hence needs to be known in order to be able to compare measured cumulated vertical distance.
- Given the large noise of the GPS altitude, I don't think it makes sense to increase the precision of the altitude to sub-metre values. At least, I haven't seen that in other GPS logs.
- What do you intended to achieve with this?  SRTM correction sounds like good idea, given the vertical offset of several dozens of meters I've observed. The offset is, however, constant over a day and thus irrelevant for measurement of altitude differences (Directly using SRTM altitude would reduce noise and apply a coarse averaging, but might introduce errors, because of errors in the data due to vegetation or buildings.)

**Comment by pherjung** [comment]
Are you planning to support Bluetooth heart rate sensors ?

**Comment by bailuk** [comment]
> Are you planning to support Bluetooth heart rate sensors ?

There are no plans so far. If you want you can start a new issue report with more details (what sensors / standards / file formats ...). Maybe (hopefully) this will then lead to something.

**Comment by mjray** [comment]
Opentopomap would be also useful for cycling with waymarkedtrails cycling overlay which is already there. Not sure if it can be added.
