### ISSUE TITLE
AAT stopped few days after an upgrade, blank screen and a crash

### ISSUE THREAD

**Issue by liori** [bailuk/AAT#63]
Hi, few days ago I've updated AAT to the most recent version. It worked fine for several days, but today every time (I tried at least five times, also twice restarting the phone) I tried launching the application, all I get is a blank black screen and, after about 20 seconds a message stating that the application stopped. I do see that it turns on the GPS sensor (I see its icon showing up on the status bar right after starting AAT and disappearing when it crashes).

Logcat Reader shows several warnings on "unknown permissions" for `ch.bailu.aat`: BODY_SENSORS, FOREGROUND_SERVICE, a "Timeout executing service: ServiceRecord{420378a8 u0 ch.bailu.aat/.services.OneService}", an ANR for the same service. I'd paste the exact logs, but I don't have means for that right now—I'll try doing so in the next few days.

This is Moto G 1st edition (falcon) running LineageOS 11 (Android 4.4.4). AAT was installed from F-Droid.

**Comment by liori** [comment]
Martin, who emailed me saying he also had a similar problem, suggested a workaround of uninstalling AAT, then installing an earlier version from F-Droid and upgrading it again. To avoid losing settings, I backed them up with Titanium Backup before uninstalling AAT, then recovered it after upgrading. Now it works fine.

**Comment by bailuk** [comment]
This is fixed in the latest release.
