### ISSUE TITLE
cursor doesn't move with GPS position

### ISSUE THREAD

**Issue by Joppla** [bailuk/AAT#66]
Hi,

I don't know if it is a bug, suspected behaviour or a setting but in Cockpit B  the cursor isn't synchronised with the GPS position, That is not very handy during cycling, I use it to know were I am.

Can you explain me if it is a bug, suspected behaviour or a setting? If setting, were can I change it? If suspected behaviour, can you make synchronising possible?

Thanks for a reaction.

**Comment by bailuk** [comment]
Tab the bottom part of the map view, then tap the 3. icon from left.

**Comment by Joppla** [comment]
thanks, it works!
