### ISSUE TITLE
Ability to use gpxtpx:hr also in imported files

### ISSUE THREAD

**Issue by vanous** [bailuk/AAT#67]
Thank you for this wonderful app! In issue https://github.com/bailuk/AAT/issues/55 , gpxtpx:hr was added for exported files, but would it be possible to also visualize this gpxtpx:hr in AAT when importing it, please?

Gadgetbridge ( https://github.com/Freeyourgadget/Gadgetbridge/ ) can export GPX from smart watches, and adds the HR, but unfortunately it is not visualized in AAT.

thank you!

**Comment by bailuk** [comment]
**gpxtpx** comes from a Garmin extension. From the [definition](https://www8.garmin.com/xmlschemas/TrackPointExtensionv1.xsd):

>   This schema defines Garmin extensions to be used with the GPX 1.1 schema.
  The root element defined by this schema is intended to be used as a child
  element of the "extensions" elements in the trkpt element in the GPX 1.1 schema. 
  The GPX 1.1 schema is available at http://www.topografix.com/GPX/1/1/gpx.xsd.
  This is a replacement for TrackPointExtension in 
  http://www.garmin.com/xmlschemas/GpxExtensions/v3

Garmin uses **TrackPointExtension** as a child element of **extensions** which was ignored by AAT. It should work now. Maybe if someone could test it before closing this issue.

The **gpxtpx:** part refers to a **namespace**. It can be ignored (if the GPX file has a valid XML declaration).

**Comment by vanous** [comment]
@bailuk thank you very much! I have tested on local build and files do open nicely with Heart Rate [bpm] charts displayed.
