### ISSUE TITLE
Improvement - Have cadence values and display more in line with basic cyclist behavior

### ISSUE THREAD

**Issue by arsab** [bailuk/AAT#68]
While time trial or Biathlete will sustain pedaling the common cyclist would have more variations 
10-20 seconds pedaling then slow down/stop for 2-3sec to recover and repeat
or up 60 seconds pedal hard to bring peloton and get back at the end stop pedaling 2-3 sec and progressivly  get to front….

Basic cyclist would most likely stop pedaling down hill.

While cyclist pedaling cycle can go up and down, typically cadence is quite constant during pedaling period most of the time.

**Current implementation average pedaling cadence with 5 samples and values displayed are significantly delayed up to 10 seconds
When cyclist stop pedaling after having cadenced at 100 values stays at 100 and do not get down to 0.**

**Proposition:
- Acknowledge that 0 is meaningful value
- We do not need to average much human body and aerodynamic does help to have quite constant values except during hard acceleration, 
  at worse can use value of 2 to keep coding style.**

see below proposed code change:

services/sensor/bluetooth_le/CscService.java   

public class CscService extends CscServiceID implements ServiceInterface {
….
**private final Averager averageCadence = new Averager(2);**     // 2 gives very much smoothing

public Attributes(BluetoothGattCharacteristic c, byte[] v) {
…..

if (haveCadence) {
    int revolutions = c.getIntValue(BluetoothGattCharacteristic.FORMAT_UINT16, offset);
    offset += 2;

    int time = c.getIntValue(BluetoothGattCharacteristic.FORMAT_UINT16, offset);

    cadence.add(time, revolutions);
    cadence_rpm = cadence.rpm();

**//**    if (cadence_rpm != 0) {
        averageCadence.add(cadence_rpm);      // include also 0 !!!
**//**    }
}

**Comment by arsab** [comment]
forgot to update delay on display refresh:

        private void broadcast() {
            if (haveSpeed && isSpeedSensor
                    && (speed_rpm != 0 || broadcasterSpeed.timeout())) {
                broadcasterSpeed.broadcast();
            }
            **if (haveCadence && isCadenceSensor) {        // broadcast even 0
                broadcasterCadence.broadcast();**
            }
        }

**Comment by bailuk** [comment]
I've added your proposal for testing.

**Comment by bailuk** [comment]
* Removed averaging of cadence: `cadence_rpm` and `cadence_rpm_average` are now identical
* Added broadcast timeout again but changed it from 3 seconds to 2 seconds: because you can't tell the difference between _crank has not turned yet_ and _crank is not turning anymore_. Now it still takes 2 seconds to get from 100 rpm to 0 rpm when cyclist stops pedaling.

**Comment by arsab** [comment]
Thanks looks working, so I close it.
