### ISSUE TITLE
How to change data directory?

### ISSUE THREAD

**Issue by Heineken** [bailuk/AAT#7]
How am I supposed to change the displayed data directory?
As AAT seems to handle my existing gpx files just fine I'd like to use the same directory as the other app. How can I do it? The folder button right next to the path under settings doesn't let me pick a folder (expected behaviour for this symbol) but let's me browse for ... I don't know what. There's no accept/select/OK button.

**Comment by bailuk** [comment]
The folder symbol on the right let's you do some operations on the **selected** directory. (such as request write permission from the OS).

As for now you can only provide a custom **base** directory (tap on the text "Data directory" and select the last item on the list to enter a custom directory).

Directory structure is explained in the [README](https://github.com/bailuk/AAT/blob/master/README.enduser.md)

(This issue stays open because a feature to provide a custom directory for GPX tracks does not exist.)

**Comment by bailuk** [comment]
Where does the _other app_ save tracks? Is it a common directory?

**Comment by Heineken** [comment]
Hi,
nice, someone reads the issues!
> The folder symbol on the right let's you do some operations on the selected directory. (such as request write permission from the OS).
Well, that's unexpected for me. Anyway, as I wrote before, I can' t OK/confirm/accept anything. Seems like it's a file picker dialog, not for directories. And there are no files shown to be selected.
> As for now you can only provide a custom base directory (tap on the text "Data directory" and select the last item on the list to enter a custom directory).
OK, also unexpected. I changed the path (here a directory picker would be nice), but as I haven't given any permissions, obviously I can't log. 
Also, I had to create the new location manually, before doing it nothing happened when I started the log.

**Comment by bailuk** [comment]
Right now if you just want tracks recorded with MyTracks to show up in AAT you have to copy all files from /Storage Card/MyTracks/gpx to /Storage Card/aat_data/activity0.

As a feature suggestion it is possible to add a menu entry to the main view of AAT that would open a track list view for /Storage Card/MyTracks/gpx (or a custom dir / or all well known dirs containing gpx files). This would, however only work if AAT has write permission to this directory (needed to store the summary database and preview images)

But maybe this is not really what you are looking for...

**Comment by bailuk** [comment]
# Some notes about the settings dialog
## The confusing directory icon
![screenshot1](https://cloud.githubusercontent.com/assets/16067257/26282872/6e104f8c-3e1a-11e7-8a34-a49d07ac8a33.png)
- The first two entries in the menu are to open the selected directory inside an external file manager. There is no standard way of doing this on Android, thats why there two entries.
- The third entry is to save the directory name to the clipboard.
- And the last one to get write permission for the selected directory (only needed in some versions of android)

## Directory list
To change the directory you get a list of defaults offered (app private, non private, internal memory, sdcard ...). The last entry lets you enter a custom directory into a text box (yes a directory picker would be nice). 
![screenshot2](https://cloud.githubusercontent.com/assets/16067257/26282942/e86c84d8-3e1c-11e7-9f5d-ae0c999b9aa5.png)

**Comment by Heineken** [comment]
OK, thanks for the screenshots. I don't have "ask for permission", although I'm running Android 6 and as described, there is an issue with the permissions. How do I get this option?

**Comment by bailuk** [comment]
It will be in the next release :-) 
I forgot that this feature didn't make it into the current release - Sorry about the confusion.

**Comment by bailuk** [comment]
Next version of AAT will support two ways for accessing the files on the device:
- **Good old Unix file system** access. Selected trough path suggestions and a text box to enter your own preferred location. Advantage: it works and it's fast. Disadvantage: Many access restrictions on Android devices and no file picker.
- Google's new **Storage Access Framework**: use the file picker to select a file path and to get access to it. Advantages: Standard Android file picker, network access, no access restrictions on device. Disadvantages: Slow, probably has a lot of bugs.

**Comment by Heineken** [comment]
OK, but should method 1 be available on Android >4 if it won't work anyway on some paths? 
Or could the access be tested immediately after setting it and, in case of failure, an error message be given?

**Comment by Heineken** [comment]
When is the new release planned?

**Comment by bailuk** [comment]
> When is the new release planned?

Next week.

> OK, but should method 1 be available on Android >4 if it won't work anyway on some paths?
Or could the access be tested immediately after setting it and, in case of failure, an error message be given?

- You will be able to choose from a list of known (and access-able including read-only) directories -> Unix
- Enter a path -> Unix
- Select a path from the system file-manager -> SAF

- Also AAT will ask for permission to access external storage on first start (some Android versions)
- Further 'android.permission.WRITE_EXTERNAL_STORAGE' is set in the APK

An error message gets displayed on first access (start tracker / open file list).  
I could add a small note to the selected path in the settings dialog like: '/storage/sdcard/aat_data (ro)'

**Comment by Heineken** [comment]
Works fine. My only issue is that after restoring the app data on with Titanium Backup a fresh system I have to think of resetting the folders so that permissions is requested and granted from the OS.
