### ISSUE TITLE
Custom maps

### ISSUE THREAD

**Issue by liori** [bailuk/AAT#72]
Hi, I can get some digitized paper maps in form of tiles. Is it possible to put them somehow into AAT's map cache and have it be served as one of the possible map sources? Thanks!

**Comment by bailuk** [comment]
What type of directory/file structure have these map-tiles?

**Comment by liori** [comment]
I'll be able to cut them into whatever tiles are necessary.

**Comment by bailuk** [comment]
Have you considered using Offline-Maps?

If you really want to use scanned maps - AAT does not support does directly. But maybe there are projects out there that let you transform scanned maps into standard map tiles. At least then it would be (theoretically) possible to save them to AATs tile cache.

**Comment by liori** [comment]
Thank you for your comment. Is this some application? I don't see anything of this name in the F-Droid repository.

**Comment by liori** [comment]
Ah, I see AAT has a feature named offline maps. Thank you, I'll try!

**Comment by SVNKoch** [comment]
For anyone stumbling across this issue. See #138 for a solution when generating tiles using in my case QGIS.
