### ISSUE TITLE
Enhancement: plus.codes

### ISSUE THREAD

**Issue by mjray** [bailuk/AAT#76]
Could the bottom left display have an option to show plus.codes as well or instead of lat/long? It seems the most widely-used of the easy-to-read free systems, largely thanks to google maps though.

I guess some way to jump to a user-entered plus code would also be useful.

**Comment by watchingJu** [comment]
This is quite useful in an app for navigation and for easy sharing locations, but I'm not sure how useful it is for a sports activity tracking app. I don't see any benefit in constantly seeing that plus code while running, cycling, ...

**Comment by mjray** [comment]
Well is there any benefit on constantly seeing long/lat either? I doubt I am the only one who uses overlays as navigation while cycling and the map mode as a general map app, POI searcher, route plotter and location sharer.

**Comment by bailuk** [comment]
You can now select 'Open Location Code (plus codes)' from the map coordinates menu. 
**Tab the right area of any map view** and then tab the icon with the **"grid" symbol** to access this menu.

If you tab the icon with the **"location" symbol** you will have different options to change or use the current map center coordinates. 
There is also a dialog that let's you enter WGS84 decimal, CH1903 and plus code coordinates (see screenshot).

Some examples of coordinates you can enter:
```
200000/600000
600.000/200000
600/200
600/200.1

geo:46.951081,7.438637
46.951081,7.438637

8fr90000+
xc2q+
+cf
```

![screenshot](https://user-images.githubusercontent.com/16067257/64921330-6b940200-d7c2-11e9-8841-96219fd265fe.jpg)
