### ISSUE TITLE
using opencyclemap as standard

### ISSUE THREAD

**Issue by Joppla** [bailuk/AAT#77]
Hi,

Is it possible to change the standard map view to the opencyclemap and how? Or is is possible to add this feature?

Thanks

**Comment by bailuk** [comment]
You can use [Waymarked Trails ](https://cycling.waymarkedtrails.org/) as an overlay to any map. 
Tap the right side of the map to access the map menu.

OpenCycleMap needs an API-key and is not implemented.

**Comment by Joppla** [comment]
Thanks for your reaction. 

Pity that I cannot add anywhere extra online maps. Like in OruxMaps. I have an API key for the open cycle maps. Maybe a request for improvement?

How to make an overlay from the waymarkedtrails? I see only 4 times a choosebox with "0". In the overlay menu.

**Comment by bailuk** [comment]
The next release will support OpenCycleMap and OpenTopoMap.

Take a look at the screenshot on how to **enable Trail-Overlays from WaymarkedTrails**. 

![image](https://user-images.githubusercontent.com/16067257/70859747-b97eea00-1f18-11ea-9e6d-8e7d69fa4200.png)
