### ISSUE TITLE
Is there a need to re-organize the auto pause feature?

### ISSUE THREAD

**Issue by Joppla** [bailuk/AAT#82]
It seems me not correct that I see no difference between the time with and without pause. See screenprint.
![Screenshot_20191029-075843_AAT](https://user-images.githubusercontent.com/25467829/67744701-23e7d380-fa1a-11e9-8570-e92a5c934489.jpg)

**Comment by bailuk** [comment]
There are two auto-pause features. Post processed auto-pause calculates auto pause to the GPX track when the track gets loaded. It doesn't modify any GPX content. While the old auto pause feature set's the tracker to pause so pauses are recorded.

Enable post processed auto-pause in the settings (General/System) and the values will change.

**Comment by bailuk** [comment]
**Is there a need to re-organize the auto pause feature?**

Currently there is "post processed auto-pause" as a global setting. And "set tracker to auto pause" feature for each activity type. 

My suggestion is to remove "set tracker to auto pause" entirely  and to move "post-processed auto-pause" to activity presets.

But maybe others still use "set tracker to auto pause" and want to keep it?

Any feedback on this?

**Comment by Joppla** [comment]
I should like to see the total ("bruto") time of the track and the "netto" time, same for the average speed.

**Comment by bailuk** [comment]
Let's move this to #84
