### ISSUE TITLE
Manual auto pause vs Postprocessed auto pause

### ISSUE THREAD

**Issue by Joppla** [bailuk/AAT#84]
See screenprint, total time (Bruto?) seems shorter then netto time. Or is the translation maybe not correct? What is named as pause seems me the total time.

Average speed netto is the same as average speed bruto. Pace with and without pause is the same.

Bruto time = Total time = netto time + pause + auto. pause.

Etc.

![20191107_122813](https://user-images.githubusercontent.com/25467829/68394822-6e79f600-0166-11ea-9245-2cda6212914f.jpg)

**Comment by bailuk** [comment]
Just enable "Post processed Auto-pause" in "Preferences -> General". Then load tracks.

This is basically issue #82

**Comment by Joppla** [comment]
@bailuk 
Thank you for your reaction

Maybe the translations to Dutch language are not done well, or is there a misunderstanding about what is what.

Let's look to the example above.
Starttime = 20:48:48
Endtime = 22:01:33
I should suspect that the "total time" [totale tijd] is Endtime - Starttime = ~ 01:13, but there is given: 00:34:54. 
If the "pause" [Pauzeer] is 00:37:54 I should suspect that "Total time without pause" [Totale tijd zonder pauses] = 01:13 - 00:37 = ~00:36. But 00:34 is shown.

Please explain me how to interpret the several times that are shown.

Thanks for reaction

**Comment by bailuk** [comment]
## You have two types of pauses: 
Manual pauses (**MP**): this is when the tracker is set to pause by you or by the "old" auto-pause feature.
Post-processed pauses (**PP**): this gets calculated when you load the track.

## How the values in the track summary are calculated:
"Totale tijd" : End Time - Start Time - **MP**
"Totale tijd (zonder pauses)" : End Time - Start Time - **MP** - **PP**

"Pauzeer" : **MP**
"Pauzeer (met autopause)" : **MP** + **PP**

**Comment by bailuk** [comment]
To make this less confusing my suggestion is still to remove _"set tracker to auto pause"_ entirely and to move _"post-processed auto-pause"_ to activity presets.

**Comment by bailuk** [comment]
If you have questions or suggestions about Autopause,feel free to open a new issue.
