### ISSUE TITLE
Feature request: Average speed while moving

### ISSUE THREAD

**Issue by Heineken** [bailuk/AAT#9]
Hey there!
I have another wish:
Please add/change the calculation of average speed while moving = distance/(time - pause)
The number will look better ;-). This is also what a bike computer usually displays.

**Comment by bailuk** [comment]
This is already the way average speed is calculated and displayed when tracking is on.
But maybe you mean something else?

**Comment by Heineken** [comment]
That's only correct when autopause is on. If I'm not mistaken, with autopause=off the absolute average including pauses is calculated,
Anyway, I am used to seeing both values: average speed including pauses and excluding pauses. That is my feature request. Then the option autopause would be obsolete (its settings would not).

**Comment by bailuk** [comment]
Ok I've added post processed auto pause. It's a global option for now. But i will make this probably per activity.  Track summary will display both "Average" and "Average AP" as well as "Pause" and "Pause AP"

**Comment by Heineken** [comment]
Cool! Thanks!
