### ISSUE TITLE
GPX files name pattern

### ISSUE THREAD

**Issue by ksz16** [bailuk/AAT#95]
First of all, I wanna thank you for a great app.

Since I have been using LineageOS without Google, I cannot activate the legally purchased version of Locus Map Pro because its developers have been refusing to add such a feature for years, although Google services are not required for the application to function properly. But now thanks to AAT I can say farewell to Locus Map forever. So thanks a lot once again.

I have a small request: could you consider change of GPX files name pattern? Now there is: YYYY_MM_DD_#.gpx. It would be nice if it also included time: YYYY_MM_DD_HH_MM.gpx. There are some rather rare situations when I use two different activities at the same day. In result I have two files with identical names e.g 2020_02_15_0 (in various folders of course). Because from time to time I export GPX files from AAT folders to one custom folder called Tracks, I have to rename one of this. Adding a timestamp would make files unique.

I would appreciate it if you would consider my request.

**Comment by bailuk** [comment]
Recorded tracks are will now have a filename like this: YYYY_MM_DD_HH_MM.gpx

``` java
public static String generateDatePrefix() {
        long time = System.currentTimeMillis();
        return String.format(Locale.ROOT,
                "%tY_%tm_%td_%tH_%tM", time, time, time, time, time);
}
```

**Comment by ksz16** [comment]
Thanks a lot for your quick reaction.
Greetings.
